### ISSUE TITLE
Q: where shuold cancelers be stored?

### ISSUE THREAD

**Issue by safareli** [lumihq/purescript-react-basic#108]
I had a situation when in didMount I was forking a fiber and storing it in state using setState and then killing the fiber in willUnmount:
```purs
activity :: Props -> JSX
activity = React.make component
  { initialState:
      { activities: []
      , canceler: mempty []
      }
  , render
  , didMount
  , willUnmount
  }
  where
    didMount self = do
      fiber <- launchAff $ getActivities >>= \activities -> do
        liftEffect $ self.setState _ {activities = activities}
      self.setState _ {canceler = fiberCanceler fiber }

    willUnmount self = launchAff_ $ un Canceler self.state.canceler $ error "willUnmount"

    render = ...
```

but in case the component was mounted and then quickly unmounted I was getting this error in console:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Signals (created by Root)
```

After further investigation it turns out the `self.setState _ {canceler = fiberCanceler fiber }` schedules state update, but it never gets executed as component is unmounted, resulting in `canceler` being mempty and `willUnmount` basically doing nothing. Because of that then once `getActivities` resolves, `setState` is called on unmounted component, and the error message is logged in console. I came across with this [issue](https://github.com/airbnb/javascript/issues/684) and it looks like for this kind of cases one should just store promise/fiber/canceler in component state `this`.

So to solve the issue i've done this:

```purs
foreign import readCanceler :: forall p s. EffectFn1 (ReactComponentInstance p s) (Nullable Canceler)
foreign import setCanceler :: forall p s. EffectFn2 (Nullable Canceler) (ReactComponentInstance p s) Unit

runCancelers :: forall p s . React.Self p s -> Effect Unit
runCancelers {instance_} = do
  canceler <- runEffectFn1 readCanceler instance_ <#> toMaybe >>> fromMaybe mempty
  launchAff_ $ un Canceler canceler $ error "runCancelers"
  runEffectFn2 setCanceler (toNullable $ Nothing) instance_

pushCanceler :: forall p s . React.Self p s -> Canceler -> Effect Unit
pushCanceler {instance_} c = do
  canceler <- runEffectFn1 readCanceler instance_ <#> toMaybe >>> fromMaybe mempty
  runEffectFn2 setCanceler (toNullable $ Just $ canceler <> c) instance_
```

```js
"use strict";

exports.readCanceler = function(instance) {
  return instance.__canceler__;
};

exports.setCanceler = function(canceler, instance) {
  instance.__canceler__ = canceler;
};
```

My question: Is there some other nicer way to deal with this? how you are dealing with similar issues?

**Comment by spicydonuts** [comment]
To be honest, we currently just ignore these warnings, at least when they occur due to a rapid mount-unmount. The warning only exists to help you find memory leaks, and this case isn't one of those.

---

In case it's helpful, the [hooks API](https://github.com/spicydonuts/purescript-react-basic-hooks) actually handles this better because you don't need to store the canceller reference anywhere:

```purs
activities /\ setActivities <- useState []

useEffect unit do
  fiber <- launchAff $ getActivities >>= \activities -> do
    liftEffect $ setActivities \_ -> activities
  pure do
    launchAff_ $ un Canceler (fiberCanceler fiber) $ error "it broke"
```

Or use the existing `useAff` helper which already handles this cancellation for you:
```purs
activitiesRes <- useAff unit getActivities
case activitiesRes of
  Nothing -> -- loading
  Just (Left err) -> -- aff error
  Just (Right activities) -> -- normal render
```

Also once React's suspend features are released this becomes something like:
```purs
-- not possible yet!
activities <- suspendAff unit getActivities
-- normal render
```
But that's probably a few months out :slightly_smiling_face:

[Here's `useAff`'s implementation](https://github.com/spicydonuts/purescript-react-basic-hooks/blob/master/src/React/Basic/Hooks/Aff.purs).

One more note -- the `unit`s in the examples above are they keys which trigger the re-running of the effects/affs. They should contain all the dependencies which change over the lifetime of the component, including props. `unit` will result in the effect only ever running one time.

**Comment by safareli** [comment]
Thanks for the answer!
