### ISSUE TITLE
Form doesn't support onSubmit

### ISSUE THREAD

**Issue by f-f** [lumihq/purescript-react-basic#45]
According to [React documentation](https://reactjs.org/docs/events.html#form-events), `form` elements should support the following events:
- `onChange`
- `onInput`
- `onInvalid`
- `onSubmit`

However, they don't seem to be accepted as props in the [definition of `form`](https://github.com/lumihq/purescript-react-basic/blob/master/src/React/Basic/DOM.purs#L679)

**Comment by justinwoo** [comment]
Keep in mind you're linking to code that is generated: https://github.com/lumihq/purescript-react-basic/blob/master/src/React/Basic/DOM.purs#L130

The problem is upstream https://github.com/lumihq/purescript-react-basic/blob/master/codegen/package.json#L8 https://github.com/jackyho112/react-html-attributes

**Comment by justinwoo** [comment]
That package now has a newer release, so someone should update the codegen project and run it again
